### ISSUE TITLE
Steamgrid processes one game then fails on Linux

### ISSUE THREAD

**Issue by GermainZ** [boppreh/steamgrid#15]
The following error is shown:

>An unexpected error occurred:

>open /home/germain/ (original).local/share/Steam/userdata/37118191/config/grid/241910.jpg: no such file or directory

`/home/germain/.local/share/Steam/userdata/37118191/config/grid/241910.jpg` is successfully created, but steamgrid seems to be checking  `/home/germain/(original).local/share/…` instead.

**Comment by boppreh** [comment]
Oh, I see the problem. Before it created the file it tried to backup the previous image by adding `(original)` at the end of the filename, but added it to the wrong location because of [this stupid line](https://github.com/boppreh/steamgrid/blob/95061fc13e01bdf9b6ee0f485f3923b4bac534be/backup.go#L32).

Totally my fault, rookie string manipulation mistake. I've already committed the fix, but unfortunately releasing a new version may take a couple of days (the pesky UI library I used got abandoned).

In the meantime, you can avoid such errors by cleaning the `/home/germain/.local/share/Steam/userdata/37118191/config/grid/` folder manually before running the program (and optionally backing up those images, if there's any image you put there yourself). This bypasses the backup process and thus this bug.

Sorry for this mistake, and thanks a lot for reporting it.

**Comment by GermainZ** [comment]
No rush. Clearing the Steam/…/config/grid/ has no effect, though -- steamgrid still fails after the first image it downloads, while trying to back it up (presumably before applying the overlay?). Cheers.

**Comment by GermainZ** [comment]
An easy workaround is to create a symbolic link to the Steam directory (such that its path contains no dots), then passing that as an argument to steamgrid.

**Comment by Gameranand** [comment]
How do I create a symbolic link to steam directory. I am noob in linux.

**Comment by boppreh** [comment]
Hi Gameranand. Answered the question in the other issue you opened. Hope that helps.

**Comment by boppreh** [comment]
Path handling code has been overhauled, fixing this and other similar bugs.

I can't reproduce the problem, but please reopen the issue if it persists.
